baseurl = "https://auto-dens.fr/"  # Include trailing slash
title = "üè† Achat / Vente de v√©hicules d'occasion"
theme = "hugo-swift-theme"
author = "Denis Freydiere"
copyright = "Copyright ¬© 2008‚Äì2022, Denis Freydiere ; all rights reserved."
canonifyurls = true
paginate = 100
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
defaultContentLanguage = 'fr'


[params]
  [params.designer]
    name = "frett27"
    url = "https://github.com/frett27"
  [[params.authors]]
    name = "autodens" # can be nickname # if fullName üëáüèª isn't set, name will be displayed on author card
    fullName = "Denis Freydiere" # optional. If set, it will display on author card
    bio = ""
    photo = "/images/logo2.svg"
    url = "https://auto-dens.fr"
  #  ga_analytics = "G-DDQ23YTTMV" # google analytics ID e.g UA-116386578-1

  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru
  # logo = "logo.png"
  # author = "Weru" # default author
  # image = "placeholder-image.png" # used whenever a page image is not set
  # blogDir = "blogFolderName" # uncomment and edit to exclude normal pages ... see issue #57
# [params.staticman]
#   endpoint = ""  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
#   gitProvider = "github"  # Either "github" or "gitlab"
#   username = "username"  # GitHub/GitLab user name
#   repository = "repo"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>

[menu]
  [[menu.main]]
    name = "√† Propos"
    url = "about/"
    weight = 2
  [[menu.main]]
    name = "Voitures"
    url = "categories/voitures/"
    weight = 3
    
    
